[versions]
appcompat = "1.6.1"
core = "1.12.0"
espresso = "3.5.1"
javaxInject = "1"
junit = "4.13.2"
junitAndroid = "1.1.5"
kotlinxCoroutines = "1.7.3"
material = "1.9.0"
agp = "8.1.2"
kotlin = "1.9.10"
hiltAndroid = "2.48"
googleServices = "4.4.0"
googleKsp = "1.9.10-1.0.13"
okhttp = "4.11.0"
retrofit = "2.9.0"
room = "2.5.3"
threetenbp = "1.6.8"
compileSdk = "34"
minSdk = "23"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
threetenbp = { module = "org.threeten:threetenbp", version.ref = "threetenbp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "googleKsp" }
