#!/usr/bin/env python3
"""
Compose Compiler Metrics checker using mendable.jar JSON output.
Parses the JSON report generated by mendable and verifies that
skippable ratio meets the given threshold.
Exits with code 1 if the threshold is not met.

Usage:
    python3 scripts/check_compose_metrics.py <mendable-json-path> [--threshold 80]
"""

import argparse
import json
import sys


def main() -> None:
    parser = argparse.ArgumentParser(description="Compose skippable ratio checker (mendable)")
    parser.add_argument(
        "report",
        help="Path to mendable JSON report file",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=100.0,
        help="Minimum required skippable ratio in percent (default: 100)",
    )
    args = parser.parse_args()

    try:
        with open(args.report, encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"::error::Report file not found: {args.report}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"::error::Failed to parse JSON report: {e}")
        sys.exit(1)

    modules = data.get("modules", [])
    if not modules:
        print("::warning::No modules found in mendable report.")
        sys.exit(0)

    print(f"Checking {len(modules)} module(s)  (threshold: {args.threshold:.0f}%)\n")

    total_restartable = 0
    total_skippable = 0
    problematic: list[str] = []

    for module_entry in modules:
        overview = module_entry.get("overview", {})
        report = module_entry.get("report", {})
        module_info = report.get("module", {})

        module_name = module_info.get("name", "unknown")
        variant = module_info.get("buildVariant", "")
        restartable = overview.get("restartableComposables", 0)
        skippable = overview.get("skippableComposables", 0)
        percentage = overview.get("skippablePercentage", 0)

        total_restartable += restartable
        total_skippable += skippable

        label = f":{module_name} ({variant})"
        print(f"  {label:<40} skippable: {skippable}/{restartable}  ({percentage}%)")

        # 문제 있는 Composable 상세 출력
        non_skippable = [
            c for c in report.get("composables", [])
            if c.get("isRestartable") and not c.get("isSkippable")
        ]
        if non_skippable:
            unstable_params = []
            for c in non_skippable:
                unstable = [
                    f"{p['name']}: {p['type']}"
                    for p in c.get("params", [])
                    if p.get("condition") == "UNSTABLE"
                ]
                entry = c["functionName"]
                if unstable:
                    entry += f"  ← unstable: {', '.join(unstable)}"
                unstable_params.append(entry)
            problematic.append((label, unstable_params))

    print()

    if total_restartable == 0:
        print("No restartable Composables found.")
        sys.exit(0)

    overall_ratio = total_skippable / total_restartable * 100
    print(f"Overall skippable ratio: {overall_ratio:.1f}%  ({total_skippable}/{total_restartable})  (threshold: {args.threshold:.0f}%)")

    if overall_ratio < args.threshold:
        non_skippable_total = total_restartable - total_skippable
        print(f"\n❌ {non_skippable_total} Composable(s) are not skippable:\n")
        for module_label, composables in problematic:
            print(f"  [{module_label}]")
            for c in composables:
                print(f"    - {c}")
        sys.exit(1)
    else:
        print(f"✅ Skippable ratio {overall_ratio:.1f}% meets the threshold ({args.threshold:.0f}%)!")


if __name__ == "__main__":
    main()
