name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Generate local.properties
        run: |
          echo $PROD_BASE_URL >> ./local.properties
          echo $DEV_BASE_URL >> ./local.properties
          cat
        env:
          PROD_BASE_URL: ${{secrets.PROD_BASE_URL}}
          DEV_BASE_URL: ${{secrets.DEV_BASE_URL}}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate local.properties
        run: |
          echo $PROD_BASE_URL >> ./local.properties
          echo $DEV_BASE_URL >> ./local.properties
          cat
        env:
          PROD_BASE_URL: ${{secrets.PROD_BASE_URL}}
          DEV_BASE_URL: ${{secrets.DEV_BASE_URL}}
      - name: Generate google-services.json
        run: |
          echo '${{secrets.GOOGLE_SERVICES}}' > ./presentation/google-services.json
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run test
        run: ./gradlew test
