name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate local.properties
        run: |
          echo $PROD_BASE_URL >> ./local.properties
          echo $DEV_BASE_URL >> ./local.properties
          echo $TERMS_URL >> ./local.properties
          cat
        env:
          PROD_BASE_URL: ${{secrets.PROD_BASE_URL}}
          DEV_BASE_URL: ${{secrets.DEV_BASE_URL}}
          TERMS_URL: ${{secrets.TERMS_URL}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate local.properties
        run: |
          echo $PROD_BASE_URL >> ./local.properties
          echo $DEV_BASE_URL >> ./local.properties
          cat
        env:
          PROD_BASE_URL: ${{secrets.PROD_BASE_URL}}
          DEV_BASE_URL: ${{secrets.DEV_BASE_URL}}

      - name: Generate google-services.json
        run: |
          echo '${{secrets.GOOGLE_SERVICES}}' > ./app/google-services.json

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run test
        run: ./gradlew test

      - name: Check Ktlint
        run: ./gradlew ktlintCheck
